FN.notNull=com.unione.cloud.beetsql.ext.FunNotNull
FN.isNotEmpty=com.unione.cloud.beetsql.ext.FunNotNull
FN.isBaseField=com.unione.cloud.beetsql.ext.FunIsBaseField
FN.isEqules=com.unione.cloud.beetsql.ext.FunIsEqules
FN.contains=com.unione.cloud.beetsql.ext.FunContains
FN.forEach=com.unione.cloud.beetsql.ext.FunForEach
TAG.sqlTrim=com.unione.cloud.beetsql.ext.TagSqlTrim
TAG.sqlWhere=com.unione.cloud.beetsql.ext.TagSqlWhere