FN.varNotNull=com.unione.cloud.beetsql.ext.FunVarNotNull
FN.isBaseField=com.unione.cloud.beetsql.ext.FunIsBaseField
TAG.sqlTrim=com.unione.cloud.beetsql.ext.TagSqlTrim
TAG.sqlWhere=com.unione.cloud.beetsql.ext.TagSqlWhere