FN.varNotNull=com.unione.cloud.beetsql.ext.FunVarNotNull
FN.isBaseField=com.unione.cloud.beetsql.ext.FunIsBaseField
FN.isEqules=com.unione.cloud.beetsql.ext.FunIsEqules
TAG.sqlTrim=com.unione.cloud.beetsql.ext.TagSqlTrim
TAG.sqlWhere=com.unione.cloud.beetsql.ext.TagSqlWhere